### ISSUE TITLE
Ansible playbook fails on Red Hat VirtualBox virtual machine.

### ISSUE THREAD

**Issue by tatwell** [chapmanu/chap-press#10]
Trello Card: https://trello.com/c/9Miy21xL/

Red Hat VM configured as documented here:

- https://wimops.chapman.edu/wiki/VirtualBox#Red_Hat_Virtual_Machine_Setup

The Ansible directory for this project needs to be reorganized to follow [best practices](https://wimops.chapman.edu/wiki/Ansible) modeled by Imposter project:

- https://github.com/chapmanu/imposter/tree/development/devops/ansible

There is currently no host file for the VM, so I added the file `virtualbox`:

```
[staging]
virtualbox ansible_host=localhost ansible_port=2222 ansible_user=wimops ansible_become_pass=chapman123
```

Then ran command:

    ansible-playbook provision.yml -i virtualbox

It failed with this error:

```
TASK [mariadb : Configure SELinux to start mysql on any port] **********************************************************
fatal: [virtualbox]: FAILED! => {"changed": false, "failed": true, "msg": "SELinux is disabled on this host."}
        to retry, use: --limit @/Users/atwell/projects/chap-press/devops/ansible/provision.retry

PLAY RECAP *************************************************************************************************************
virtualbox                 : ok=16   changed=12   unreachable=0    failed=1   
```

**Comment by tatwell** [comment]
Playbook can be updated to assume SELinux is already disabled on the box.

**Comment by spence-man** [comment]
Issue closed due to overhaul update to Ansible directory. Ansible setup tested and working via the Chapman blogs repo.
