### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by spence-man** [chapmanu/chap-press#19]
### MariaDB
-  If the MariaDB has not been used before, the MySQL database may have to be restarted or unlinked using Homebrew:

    brew services stop mysql
    brew services list
    brew unlink mysql
    brew link mariadb
    brew services start mariadb

- ERROR 1290 --skip-grant-tables option Error

If you see this error when trying to create or grant privileges to a MYSQL user:

    ERROR 1290 (HY000): The MySQL server is running with the --skip-grant-tables
    option so it cannot execute this statement

Run `FLUSH PRIVILEGES;` first then run the command.

[Skip-grant Source](https://unix.stackexchange.com/a/102916)

**Comment by tatwell** [comment]
After following steps above, I was having issue described here:

- https://stackoverflow.com/questions/2933415/mysql-mac-error-2002-cant-connect-to-local-through-socket

Using `mysql.server start` revealed the problem:

```
$ brew services start mariadb
==> Successfully started `mariadb` (label: homebrew.mxcl.mariadb)
$ mysql -uroot
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
$ mysql.server start
Starting MySQL
.171020 12:39:06 mysqld_safe Logging to '/usr/local/var/mysql/SMC-MBOOKP13-01.err'.
rm: /usr/local/var/mysql/SMC-MBOOKP13-01.pid: Permission denied
171020 12:39:06 mysqld_safe Fatal error: Can't remove the pid file:
/usr/local/var/mysql/SMC-MBOOKP13-01.pid
Please remove it manually and start /usr/local/Cellar/mariadb/10.2.9/bin/mysqld_safe again;
mysqld daemon not started
/usr/local/Cellar/mariadb/10.2.9/bin/mysqld_safe_helper: Can't create/write to file '/usr/local/var/mysql/SMC-MBOOKP13-01.err' (Errcode: 13 "Permission denied")
```

A permissions issue. This fixed it:

```
$ sudo chown -Rv $(whoami) /usr/local
```
