### ISSUE TITLE
Error with IUS install when installing PHP through Ansible

### ISSUE THREAD

**Issue by spence-man** [chapmanu/chap-press#23]
I don’t think it’s an error with the role. Never had any issues before and there are no modifications to it. I believe it is something with either the RH package manager or some Epel repo issue. When I manually try to install IUS, I receive a similar error log message and no action is taken. The yum repo might just need some update or some other version confliction.  

**Ansible PHP error**: 

```
Error: TASK [chusiang.php7 : Install ius from remote repo]  
```
```
fatal: [virtualbox]:  
FAILED! => {
  "changed": true, 
  "cmd": ["bash", "/tmp/setup-ius.sh"], 
  "delta": "0:00:01.301220", 
  "end": "2017-11-02 11:39:52.531615", 
  "failed": true, "rc": 1, 
  "start": "2017-11-02 11:39:51.230395", 
  "stderr": "Error: Nothing to do", 
  "stderr_lines": ["Error: Nothing to do"], 
  "stdout": "detected RHEL 7.2\nEL 7 is supported\nLoaded plugins: enabled_repos_upload, 
   package_upload, 
   product-id, 
   search-\n : disabled-repos, 
   subscription-manager\nExamining /var/tmp/yum-root-lzRCyg/epel-release-latest-7.noarch.rpm: 
   epel-release-7-11.noarch\n/var/tmp/yum-root-lzRCyg/epel-release-latest-7.noarch.rpm: does 
   not update installed package.\nUploading Enabled Repositories Report\nLoaded plugins: 
   product-id", 
   "stdout_lines": ["detected RHEL 7.2", "EL 7 is supported", "Loaded plugins:  
  enabled_repos_upload, package_upload, product-id, search-", " : disabled-repos, subscription-
  manager", "Examining /var/tmp/yum-root-lzRCyg/epel-release-latest-7.noarch.rpm: epel-
  release-7-11.noarch", "/var/tmp/yum-root-lzRCyg/epel-release-latest-7.noarch.rpm: does not 
  update installed package.", "Uploading Enabled Repositories Report", "Loaded plugins: product-
  id"]}
```

**Comment by tatwell** [comment]
That message is really weird: `Error: Nothing to do`? I recently had to rerun the registration script on my virtualbox snapshot after it expired (I guess). See here:

- https://wimops.chapman.edu/wiki/VirtualBox#Subscription_Expiration

Then there's the possibility of random intermittent issues, like a network hiccup. I've had issues where something will fail and then, when I run it again, it works.

**Comment by spence-man** [comment]
Ok, I'll look into the expiration part. I've rerun the RH vm install a couple times. Overall the guide and install works smoothly. Hopefully some solution will come up.

**Comment by spence-man** [comment]
Ansible reorganized and working via Blogs Chapman repo.
