### ISSUE TITLE
Not able to configure Ansible SSL role to work properly

### ISSUE THREAD

**Issue by spence-man** [chapmanu/chap-press#5]
I added an SSL role from [this](https://github.com/jdauphant/ansible-role-ssl-certs) repo. The server runs fine on `http` but the configuration is not setup for `https`.  I've been looking at how the server templates are configured on the nginx server. When I add the ssl certificates to the server template there are errors. The redirection from http to https is also another part I couldn't sort out.

**Comment by tatwell** [comment]
What are the errors you are seeing? Have you tried going on the server and running this command:

    sudo nginx -t

That should identify the issue if it's something with the nginx config file.

This link describes how to set up a SSL certificate for nginx manually and may help with troubleshooting:

- https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-on-centos-7

**Comment by spence-man** [comment]
Yes, I followed that tutorial. Everything seemed to work except the redirect. I would enter in https://localhost:5555 and it would be fine.   But going to  http://localhost:5555 would fail  (This site can’t be reached) and the url is weird (https://localhost//)

**Comment by spence-man** [comment]
No errors from sudo nginx -t .

**Comment by spence-man** [comment]
I'll keep looking at the article and see if I can rearrange some of my ansible roles

**Comment by tatwell** [comment]
http and https are on different ports. Defaults are 80 and 443 respectively. See here for how I config them for VirtualBox:

- https://wimops.chapman.edu/wiki/VirtualBox#Add_Hardware_.2F_Network_Support

**Comment by spence-man** [comment]
UPDATE: I configured certificates and nginx and updated repo. The chappress server redirects to https with the welcome screen. I used the digital ocean guide you added earlier. The issue I'm working on now is that the browser doesn't recognize the certificate at first. They make a note in the article:

> Note: A self-signed certificate will encrypt communication between your server and any clients. However, because it is not signed by any of the trusted certificate authorities included with web browsers, users cannot use the certificate to validate the identity of your server automatically.  

> A self-signed certificate may be appropriate if you do not have a domain name associated with your server and for instances where the encrypted web interface is not user-facing. If you do have a domain name, in many cases it is better to use a CA-signed certificate.

**Comment by spence-man** [comment]
I'll continue looking into that self-signed certificate issue.

**Comment by tatwell** [comment]
@spence-man Don't worry about the browser warning. That's expected. It's ok with staging servers. Staging is just for testing and users know to click past the warning.

For production servers, IS&T installs commercial certificates so the warning won't appear.

**Comment by tatwell** [comment]
I can access server as expected now:

- https://chappress-staging.chapman.edu/

You can close this issue. Please briefly not what you did to resolve this for future reference.

**Comment by spence-man** [comment]
**RESOLVED:** I rearranged the order of role operations with SSL first and then nginx. I added some custom edits to this [ssl role](https://github.com/jdauphant/ansible-role-ssl-certs).  I reformatted the nginx server [template](https://www.bjornjohansen.no/redirect-to-https-with-nginx) to redirect to https. I use this [guide](https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu-16-04) as a general resource for setting up ssl on nginx.
