### ISSUE TITLE
Wonolog is not displaying log folder

### ISSUE THREAD

**Issue by spence-man** [chapmanu/chap-press#8]
Wonolog works on my local machine, with the Wonolog logging folders being added to `wp-content`. The same configuration used on the staging server does not produce the standard Wonolog logging folders. I have tested different options restarting server/php-fpm, redeploying using Capistrano, checked folder permissions, verified vendor package exists, all versions of the requirements are valid.

**Comment by spence-man** [comment]
The process I followed is based on the setup guide for Wonolog. These are the setup steps I followed and they worked on my local setup but not the staging.
[Wonolog Github](https://github.com/inpsyde/Wonolog)


To get started with defaults settings, this is required:
1. Install Wonolog via Composer;
2. Ensure Composer autoload is loaded in wp-config.php or anytime before the 'muplugins_loaded' action is fired;
3. create a MU plugin that, at least, contains this code:
```
<?php
    Inpsyde\Wonolog\bootstrap();
```

**Comment by spence-man** [comment]
- To install Composer on the staging server, I added an Ansible Role at `devops/ansible/roles/common` .
- To install the composer packages on the staging server, I added a task for Capistrano at `config/deploy.rb`

Might be a better solution, but these worked for the moment.

**Comment by tatwell** [comment]
Since this project is following the example of Blogs, the MU plugin should be in source control and deployed by Capistrano. Is that the case?

**Comment by spence-man** [comment]
The MU plugin was only added to the public repo and will be included during the deploy.

**Comment by spence-man** [comment]
Issue sorted due to the permissions restriction on the `wp-content` folder. Fix is at `config/deploy.rb` with a task that allows the `wp-content` folder writable permissions. Added code:
  
```
sudo chown php-fpm:webadmin -R #{release_path}/content
sudo find #{release_path}/content -type d -exec chmod 775 {} \\; 
```

Another fix was providing the right path file for autoloading composer. See `config/templates/wp-config.php.erb` at Line 73. The `$autoload_path` variable ensures composer is autoloaded from the current Capistrano release path. This requirement is stated in the Wonolog [install guide](https://github.com/inpsyde/Wonolog).
