### ISSUE TITLE
Various installation issues.

### ISSUE THREAD

**Issue by tatwell** [chapmanu/chap-press#9]
Trello Card: https://trello.com/c/SmvcHE6y

I installing from scratch following the README using the latest version of `master` branch. This issue will track minor issues I encounter.

- [x] `wp_core_install` step: see comment below
- [x] `codecept run` only runs 4 unit tests: I thought we had examples of all types of tests.
- [x] Move **Codeception Commands** section to wiki page: TMI for README.
- [x] Move Ansible subsection in Install section down to Ansible section.
- [x] Typo: `sudo easy_install pip/`` (extra tick at end)
- [x] For **Troubleshooting** section, create Github issue for each issue listed there and then link to it.

**Comment by tatwell** [comment]
### wp_core_install issue

```
$ wp core install --url=http://localhost:8222/ --title=chap-press --admin_user=chappress --admin_password=password --admin_email=chappress@gmail.com
WordPress is already installed.
```

Is this step needed still?

Actually, this may be because I had already created a database. I'll try removing it.

Yes, that was the issue. Needed to recreate databases:

```
mysql -u root
> DROP DATABASE chappress_dev; CREATE DATABASE chappress_dev;
> DROP DATABASE chappress_test; CREATE DATABASE chappress_test;
> exit
```

Then command worked and I was able to log into dashboard on local dev server.

**Comment by spence-man** [comment]
@tatwell Should I create a separate branch for these fixes? or just include them for the `active-directory`?

**Comment by tatwell** [comment]
@spence-man Ignore this for now. I'll create a Trello card for this. You should always be working from a Trello card. (If you ever aren't for some reason, let me know.)
